In [3]:
import numpy as np

In [4]:
arr = np.array([23, 45, 67, 89, 10])

In [5]:
print(arr)

[23 45 67 89 10]


In [6]:
arr

array([23, 45, 67, 89, 10])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr[2]

67

In [9]:
arr[2] = 100

In [10]:
arr # it is mutable

array([ 23,  45, 100,  89,  10])

In [11]:
arr1 =[23, 45, 100, 89, 10]

In [12]:
arr1

[23, 45, 100, 89, 10]

In [13]:
arr1 = np.array([12, 34, 98, 55, True, "Pune"])

In [14]:
arr1          # it is hetrogeneous

array(['12', '34', '98', '55', 'True', 'Pune'], dtype='<U11')

In [15]:
arr1.dtype

dtype('<U11')

In [16]:
arr

array([ 23,  45, 100,  89,  10])

In [17]:
arr * 2

array([ 46,  90, 200, 178,  20])

In [18]:
 # check which one is faster.......list or array 

In [19]:
import time

In [20]:
time.time()

1753027747.1234896

In [21]:
s = 100000
list1 = list(range(s))
arr1 = np.array(list1)

In [22]:
list1

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [23]:
# for list

In [24]:
start_time = time.time()
x = [i * 2 for i in list1]
time_list = time.time() - start_time
print("time taken by list:", time_list)

time taken by list: 0.006999969482421875


In [25]:
# for array

In [26]:
start_time = time.time()
y = arr1 * 2
time_arr = time.time() - start_time
print("time taken by list:", time_arr)

time taken by list: 0.000995635986328125


In [27]:
time_list / time_arr

7.030651340996169

#### arange

In [28]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a = np.arange(20, 31)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
arr

array([ 23,  45, 100,  89,  10])

In [35]:
arr.ndim

1

#### 2-d arrays

In [36]:
arr = np.array([[1, 2, 3], [4, 2, 5], [6, 9, 4], [6, 3, 8]])

In [37]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [38]:
arr.ndim

2

In [39]:
arr.size

12

In [40]:
arr.shape

(4, 3)

In [41]:
arr.flatten()

array([1, 2, 3, 4, 2, 5, 6, 9, 4, 6, 3, 8])

In [42]:
arr.flatten().ndim

1

In [43]:
arr.reshape(6, 2)

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 9],
       [4, 6],
       [3, 8]])

In [44]:
arr.reshape(2, -1)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 8]])

In [45]:
arr.reshape(3, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[2, 5],
        [6, 9]],

       [[4, 6],
        [3, 8]]])

#### slicing

In [46]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [47]:
arr1 = np.arange(3, 13)
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
arr1[3:7]

array([6, 7, 8, 9])

In [49]:
arr[1:3, 0:2]

array([[4, 2],
       [6, 9]])

In [50]:
arr[1:3, 0:3]

array([[4, 2, 5],
       [6, 9, 4]])

In [51]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
np.mean(arr1)

7.5

In [53]:
np.std(arr1)

2.8722813232690143

In [54]:
# linear alg #

In [55]:
a = np.array([[1,4], [4,9]])
b = np.array([[3,3], [10,1]])

In [56]:
a

array([[1, 4],
       [4, 9]])

In [57]:
b

array([[ 3,  3],
       [10,  1]])

In [58]:
a @ b

array([[ 43,   7],
       [102,  21]])

In [59]:
np.dot(a,b)

array([[ 43,   7],
       [102,  21]])

In [60]:
a

array([[1, 4],
       [4, 9]])

In [61]:
np.linalg.det(a)

-6.999999999999999

In [62]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [63]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

In [64]:
# vector

vec = np.array([3, 6])

In [65]:
np.linalg.norm(vec)

6.708203932499369

In [66]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.

    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.

    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of th

### Practice questions

In [67]:
# 1.create a numpy array of shape(3, 3) with values ranging from 1 to 9

In [68]:
arr1 = np.arange(1, 10)

In [69]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr1.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# 2.given a 1D numpy array[10,20,30,40,50], write code to reverse the array

In [72]:
arr = [10, 20, 30, 40, 50]
reversed_arr = arr[::-1]
print (reversed_arr)

[50, 40, 30, 20, 10]


In [73]:
# 3.create a 5x5 numpy array filled with zeros and set the value of the middle element to 1.

In [74]:
array = np.zeros((5,5), dtype=int)
array[2, 2] = 1
print(array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [75]:
# 4.Generate a NumPy array with 20 random integers between 1 and 100. Replace all even numbers with -1

In [76]:
arr = np.random.randint(1, 101, size=20)  
arr[arr % 2 == 0] = -1  
print(arr)

[-1 79 89 89 -1 -1 -1 -1 31 43 -1 89 -1 31 57 -1 -1 -1 51 11]


In [77]:
# 5.Extract the second column from a 2D NumPy array

In [78]:
a = np.array([[1, 2], [3, 4], [5, 6]])
ex_arr = a[:, 1]
print(a)
print("-----------")
print(ex_arr)

[[1 2]
 [3 4]
 [5 6]]
-----------
[2 4 6]


In [79]:
# 6.Create a NumPy array and convert to 2x2 matrix

In [80]:
arr = np.array([1, 2, 3, 4])
matrix = arr.reshape(2, 2)
print("2x2 Matrix:\n", matrix)

2x2 Matrix:
 [[1 2]
 [3 4]]


In [81]:
# 7.element-wise operations on two 2x2 arrays

In [82]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:\n", add)
print("---------------------")
print("Subtraction:\n", sub)
print("---------------------")
print("Multiplication:\n", mul)
print("---------------------")
print("Division:\n", div)

Addition:
 [[ 6  8]
 [10 12]]
---------------------
Subtraction:
 [[-4 -4]
 [-4 -4]]
---------------------
Multiplication:
 [[ 5 12]
 [21 32]]
---------------------
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [84]:
# 8.10_linearly spaced values between 0 and 1

In [85]:
linear_values = np.linspace(0, 1, 10)
print("Linearly spaced values:\n", linear_values)

Linearly spaced values:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
help(np.mean)

In [ ]:
help(np.median)

In [ ]:
data = np.array([10, 20, 30, 40, 50])

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

In [ ]:
def normalize_col(arr):
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0)
    std[std == 0] = 1
    return (arr - mean) / std

data = np.array([[1, 2], [3, 4], [5, 6]])
normalized = normalize_col(data)
print("Normalized array:\n", normalized)